[package]
name = "fs"
version = "0.1.0"
edition = "2021"


[dependencies]
bitflags = { version = "1.3.2", default-features = false }
# We use libc for its type definitions
libc = "0.2.137"
sc = "0.2.7"

[dev-dependencies]
