name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  x86_64-unknown-linux-gnu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format check
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
